# Generated by Django 5.0.7 on 2026-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
