# Generated by Django 5.0.7 on 2024-08-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='mark_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='homework_assignments',
            field=models.ManyToManyField(blank=True, related_name='students', through='core.StudentHomework', to='core.homework'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='core.homework'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_details', to='core.student'),
        ),
    ]
