# Generated by Django 5.0.7 on 2026-04-12 04:42

import django.db.models.deletion
from django.db import migrations, models


def copy_student_word_m2m_to_lexicon(apps, schema_editor):
    StudentLexiconEntry = apps.get_model('core', 'StudentLexiconEntry')
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT student_id, word_id FROM core_student_words')
        rows = cursor.fetchall()
    for student_id, word_id in rows:
        StudentLexiconEntry.objects.get_or_create(student_id=student_id, word_id=word_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_avatar_homework_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentLexiconEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicon_entries', to='core.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lexicon_entries', to='core.word')),
            ],
        ),
        migrations.RunPython(copy_student_word_m2m_to_lexicon, noop_reverse),
        migrations.RemoveField(
            model_name='student',
            name='words',
        ),
        migrations.AddField(
            model_name='student',
            name='words',
            field=models.ManyToManyField(
                blank=True,
                related_name='students',
                through='core.StudentLexiconEntry',
                through_fields=('student', 'word'),
                to='core.word',
            ),
        ),
        migrations.AddConstraint(
            model_name='studentlexiconentry',
            constraint=models.UniqueConstraint(fields=('student', 'word'), name='core_lexicon_student_word_uniq'),
        ),
    ]
