# Generated by Django 5.0.7 on 2024-07-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_groups_user_is_active_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='homework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_words', to='core.homework'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='class_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_classes', to='core.class'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='reading',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='homework_related', to='core.word'),
        ),
    ]
