# Generated by Django 5.0.7

from django.db import migrations


def backfill_answers(apps, schema_editor):
    StudentHomework = apps.get_model('core', 'StudentHomework')
    for sh in StudentHomework.objects.select_related('homework').iterator():
        questions = sh.homework.questions
        if not isinstance(questions, list):
            questions = []
        n = len(questions)
        cur = sh.answers
        if isinstance(cur, list):
            out = []
            for i in range(n):
                if i < len(cur) and cur[i] is not None:
                    out.append(str(cur[i]))
                else:
                    out.append('')
        else:
            out = [''] * n
        StudentHomework.objects.filter(pk=sh.pk).update(answers=out)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lexicon_entry_and_due_date'),
    ]

    operations = [
        migrations.RunPython(backfill_answers, noop_reverse),
    ]
