# Generated by Django 5.0.7

from django.db import migrations


def convert_answers_to_rows(apps, schema_editor):
    StudentHomework = apps.get_model('core', 'StudentHomework')
    for sh in StudentHomework.objects.select_related('homework').iterator():
        questions = sh.homework.questions
        if not isinstance(questions, list):
            questions = []
        cur = sh.answers
        out = []
        for i, q in enumerate(questions):
            if isinstance(q, dict):
                text = str(q.get('question') or q.get('q') or '').strip()
            else:
                text = ''
            ans = ''
            if isinstance(cur, list) and i < len(cur):
                cell = cur[i]
                if isinstance(cell, dict):
                    ans = str(cell.get('answer') or '')
                elif cell is not None:
                    ans = str(cell)
            out.append({'question': text, 'answer': ans})
        StudentHomework.objects.filter(pk=sh.pk).update(answers=out)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_student_homework_answers'),
    ]

    operations = [
        migrations.RunPython(convert_answers_to_rows, noop_reverse),
    ]
