# Generated by Django 5.0.7 on 2024-07-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_word_homework_alter_homework_class_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='homework',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homework_words', to='core.homework'),
            preserve_default=False,
        ),
    ]
