# Generated by Django 5.0.7

from django.db import migrations


def rebuild_all_lexicons(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    StudentLexiconEntry = apps.get_model('core', 'StudentLexiconEntry')
    StudentHomework = apps.get_model('core', 'StudentHomework')
    for student in Student.objects.all().iterator():
        StudentLexiconEntry.objects.filter(student=student).delete()
        for sh in StudentHomework.objects.filter(student=student, marked=True).order_by('id').iterator():
            for word in sh.homework.words.all():
                StudentLexiconEntry.objects.get_or_create(student=student, word=word)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studenthomework_answers_object_rows'),
    ]

    operations = [
        migrations.RunPython(rebuild_all_lexicons, noop_reverse),
    ]
