# Generated by Django 5.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rebuild_lexicon_from_marked_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='words',
        ),
        migrations.DeleteModel(
            name='StudentLexiconEntry',
        ),
    ]
