# Generated by Django 5.0.7 on 2026-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teacher_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='demo_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
